//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkingDiary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class working_diaryEntities : DbContext
    {
        public working_diaryEntities()
            : base("name=working_diaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<diary> diary { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<settings> settings { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
